// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYnflgy51aqcgwUOJFp0vuPl_GZq8Fw4',
    appId: '1:879155598340:web:11381569659192f8535151',
    messagingSenderId: '879155598340',
    projectId: 'test-1-d0413',
    authDomain: 'test-1-d0413.firebaseapp.com',
    storageBucket: 'test-1-d0413.firebasestorage.app',
    measurementId: 'G-F39EM481LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz-yY9RYq753s4d8o0c_44lQDBcFJPWnc',
    appId: '1:879155598340:android:840336068b3484d5535151',
    messagingSenderId: '879155598340',
    projectId: 'test-1-d0413',
    storageBucket: 'test-1-d0413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDNdpYEUW2lF8wNR7i9wXSKOO1gcmmn4',
    appId: '1:879155598340:ios:a09ede93309ab779535151',
    messagingSenderId: '879155598340',
    projectId: 'test-1-d0413',
    storageBucket: 'test-1-d0413.firebasestorage.app',
    iosBundleId: 'com.example.habitsNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoDNdpYEUW2lF8wNR7i9wXSKOO1gcmmn4',
    appId: '1:879155598340:ios:a09ede93309ab779535151',
    messagingSenderId: '879155598340',
    projectId: 'test-1-d0413',
    storageBucket: 'test-1-d0413.firebasestorage.app',
    iosBundleId: 'com.example.habitsNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqYnflgy51aqcgwUOJFp0vuPl_GZq8Fw4',
    appId: '1:879155598340:web:4a4470c712f14e3a535151',
    messagingSenderId: '879155598340',
    projectId: 'test-1-d0413',
    authDomain: 'test-1-d0413.firebaseapp.com',
    storageBucket: 'test-1-d0413.firebasestorage.app',
    measurementId: 'G-M94BXS9T8M',
  );
}
